### ISSUE TITLE
无法再 build里加载

### ISSUE THREAD

**Issue by wwwwwwwwwwj** [relish-wang/VehicleEditText#1]
ERROR: Failed to resolve: wang.relish.widget:vehicleedittext:1.0.0

**Comment by xuelangren** [comment]
无法加载是因为要在项目的总gradle 里面加上一句话
allprojects {
    repositories {
        google()
        jcenter()


        maven { url "https://oss.sonatype.org/content/groups/public" } // 添加这行
        
    }

**Comment by xuelangren** [comment]
> ERROR: Failed to resolve: wang.relish.widget:vehicleedittext:1.0.0

无法加载是因为要在项目的总gradle 里面加上一句话
allprojects {
repositories {
google()
jcenter()

    maven { url "https://oss.sonatype.org/content/groups/public" } // 添加这行
    
}

**Comment by relish-wang** [comment]
已修复。请尝试使用最新的版本进行验证。
