### ISSUE TITLE
在自定义dialog中，弹出软键盘和dialog不在同个层级，

### ISSUE THREAD

**Issue by TroyIrvo** [relish-wang/VehicleEditText#10]
定义EditText, 然后触发车牌号软键盘，发现被dialog遮罩层遮挡，无法点击。

**Comment by TroyIrvo** [comment]
目前的做法是，设置给软键盘view 高于dialog的层级。使得软键盘一直再dialog上方。

**Comment by huaxuanHan** [comment]
请教一下，怎么设置的层级啊
