### ISSUE TITLE
横屏的时候那个删除按钮太长，变形

### ISSUE THREAD

**Issue by xuelangren** [relish-wang/VehicleEditText#2]
这个在使用的时候发现横屏的时候那个删除按钮会变形，很丑，同时希望能对车牌号长度进行限制！谢谢！

**Comment by relish-wang** [comment]
已修复。

**Comment by relish-wang** [comment]
1 已添加了横屏时用的删除按钮图标；
2 由于新能源车牌号和地方武警的车牌号是8位的, 所以现在做的限制是8位。如果有需要限制，建议你拷贝我的源码修改后进行使用。
